name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Build Virtual environment + Install dependencies and package
      run: |
        cd Workers/ants
        python -m venv pygame-3.6
        source pygame-3.6/bin/activate
        pip install -e .
    - name: Test with unittest
      run: |
        python -m unittest discover
